name: droplet_classification_env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - python=3.11.13
  - numpy=2.3.1
  - pandas=2.3.0
  - scipy=1.15.2
  - scikit-learn=1.7.1
  - pillow=11.2.1
  - opencv=4.12.0
  - matplotlib-base=3.10.3
  - seaborn=0.13.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - pip=25.1.1
  - yaml
  - pip:
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - xgboost==3.0.2
      - umap-learn